# Generated by Django 5.2.13 on 2026-04-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrolment_Form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customform',
            options={'ordering': ['school__name', 'section_number']},
        ),
        migrations.AlterUniqueTogether(
            name='customform',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customform',
            name='section_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='customform',
            constraint=models.UniqueConstraint(fields=('school', 'section_number'), name='unique_customform_section_per_school'),
        ),
    ]
